# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
       - run:|
         git fetch --tags
         git branch --create-reflog main origin/main
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release --nologo --verbosity minimal /maxcpucount
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
    - name: Test
      run: dotnet test --verbosity normal
    
    - name: Install GitVersion
      run: dotnet tool install --global GitVersion.Tool

    - name: Versioning
      env:
        BUILD_REVISION: ${{ github.sha }}
      run: |
        dotnet gitversion /updateassemblyinfo
        dotnet build --no-restore
